#!/usr/bin/env python3
"""Validate and pack the tracked TinyViT FC2 K=512 activation slice."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tempfile
from typing import Any

from prepare_tinyvit_fc1_k128 import (
    CHUNK_K,
    FC2_OUTPUT_CHANNELS,
    TOKENS,
    chunk_words,
    fc2_lowest_l1_group_masks,
    fc2_masked_window_outputs,
    require_matrix,
)


SCHEMA = "sap-vpu-tinyvit-fc2-k512-int8-v1"
INPUT_CHANNELS = 512
CHUNKS = INPUT_CHANNELS // CHUNK_K
GLOBAL_DROP_COUNT = 16


def validate(raw: Any) -> tuple[list[list[int]], list[list[int]], list[list[int]]]:
    if not isinstance(raw, dict) or raw.get("schema") != "sap-vpu-tinyvit-mlp2-int8-v1":
        raise ValueError("invalid parent TinyViT activation fixture")
    fixture = raw.get("fc2_k512")
    if not isinstance(fixture, dict) or fixture.get("schema") != SCHEMA:
        raise ValueError(f"missing {SCHEMA} fixture")
    if fixture.get("chunk_k") != CHUNK_K:
        raise ValueError(f"fc2_k512.chunk_k must be {CHUNK_K}")
    inputs = require_matrix(fixture.get("input_tokens"), "input_tokens", TOKENS, INPUT_CHANNELS)
    weights = require_matrix(
        fixture.get("weights"), "weights", FC2_OUTPUT_CHANNELS, INPUT_CHANNELS
    )
    expected = fixture.get("expected_integer_output")
    if (
        not isinstance(expected, list)
        or len(expected) != TOKENS
        or any(
            not isinstance(row, list)
            or len(row) != FC2_OUTPUT_CHANNELS
            or any(not isinstance(value, int) or isinstance(value, bool) for value in row)
            for row in expected
        )
    ):
        raise ValueError("expected_integer_output must have integer shape [2, 2]")
    calculated = [
        [
            sum(inputs[token][k] * weights[output][k] for k in range(INPUT_CHANNELS))
            for output in range(FC2_OUTPUT_CHANNELS)
        ]
        for token in range(TOKENS)
    ]
    if calculated != expected:
        raise ValueError("FC2 K=512 golden does not match INT8 inputs and weights")
    return inputs, weights, [list(row) for row in expected]


def masked_aggregate(
    inputs: list[list[int]], weights: list[list[int]], masks: list[int]
) -> list[list[int]]:
    windows = fc2_masked_window_outputs(inputs, weights, masks)
    return [
        [sum(window[token][output] for window in windows) for output in range(FC2_OUTPUT_CHANNELS)]
        for token in range(TOKENS)
    ]


def write_svh(
    path: Path,
    inputs: list[list[int]],
    weights: list[list[int]],
    dense_expected: list[list[int]],
) -> None:
    policies = {
        "GLOBAL_L1_6P25": fc2_lowest_l1_group_masks(weights, drop_count=GLOBAL_DROP_COUNT),
        "L1_BUDGET_2PCT": fc2_lowest_l1_group_masks(weights, l1_budget=0.02),
    }
    lines = ["/* Generated by prepare_tinyvit_fc2_k512.py; do not edit. */"]
    for name, words in (
        ("TINYVIT_FC2_K512_INPUT_WORDS", chunk_words(inputs, INPUT_CHANNELS)),
        ("TINYVIT_FC2_K512_WEIGHT_WORDS", chunk_words(weights, INPUT_CHANNELS)),
    ):
        lines.append(f"localparam logic [31:0] {name} [0:{len(words) - 1}] = '{{")
        lines.append("  " + ", ".join(f"32'h{word:08x}" for word in words))
        lines.append("};")
    for name, masks in policies.items():
        lines.append(f"localparam logic [3:0] TINYVIT_FC2_K512_{name}_MASKS [0:{len(masks) - 1}] = '{{")
        lines.append("  " + ", ".join(f"4'h{mask:x}" for mask in masks))
        lines.append("};")
    expected = {
        "DENSE": dense_expected,
        **{name: masked_aggregate(inputs, weights, masks) for name, masks in policies.items()},
    }
    for name, matrix in expected.items():
        values = [value for row in matrix for value in row]
        lines.append(f"localparam logic [31:0] TINYVIT_FC2_K512_{name}_EXPECTED [0:3] = '{{")
        lines.append("  " + ", ".join(f"32'h{value & 0xffffffff:08x}" for value in values))
        lines.append("};")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def self_test() -> None:
    root = Path(__file__).resolve().parents[1]
    raw = json.loads(
        (root / "sw/baremetal/fixtures/tinyvit_mlp2_activation.json").read_text(encoding="ascii")
    )
    inputs, weights, expected = validate(raw)
    assert expected == [[4760, -5014], [-1239, -7509]]
    assert len(chunk_words(inputs, INPUT_CHANNELS)) == 256
    assert len(chunk_words(weights, INPUT_CHANNELS)) == 256
    global_masks = fc2_lowest_l1_group_masks(weights, drop_count=GLOBAL_DROP_COUNT)
    budget_masks = fc2_lowest_l1_group_masks(weights, l1_budget=0.02)
    assert len(global_masks) == CHUNKS
    assert sum(4 - bin(mask).count("1") for mask in global_masks) == GLOBAL_DROP_COUNT
    assert 0 < sum(4 - bin(mask).count("1") for mask in budget_masks) < CHUNKS * 4
    assert global_masks == budget_masks
    assert masked_aggregate(inputs, weights, global_masks) == [[4659, -4532], [-909, -6957]]
    assert masked_aggregate(inputs, weights, [0xF] * CHUNKS) == expected
    with tempfile.TemporaryDirectory() as directory:
        output = Path(directory) / "fixture.svh"
        write_svh(output, inputs, weights, expected)
        generated = output.read_text(encoding="ascii")
        assert "TINYVIT_FC2_K512_INPUT_WORDS [0:255]" in generated
        assert "TINYVIT_FC2_K512_WEIGHT_WORDS [0:255]" in generated
        assert "TINYVIT_FC2_K512_GLOBAL_L1_6P25_MASKS [0:63]" in generated
        assert "TINYVIT_FC2_K512_L1_BUDGET_2PCT_MASKS [0:63]" in generated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fixture", type=Path, nargs="?")
    parser.add_argument("--svh", type=Path)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    try:
        if args.self_test:
            if args.fixture or args.svh:
                parser.error("--self-test does not accept fixture output arguments")
            self_test()
        elif not args.fixture or not args.svh:
            parser.error("fixture and --svh are required")
        else:
            inputs, weights, expected = validate(
                json.loads(args.fixture.read_text(encoding="ascii"))
            )
            write_svh(args.svh, inputs, weights, expected)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"TinyViT FC2 K=512 fixture failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
