#!/usr/bin/env python3
"""Validate and pack the tracked TinyViT FC1 K=128 activation slice."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tempfile
from typing import Any

from prepare_tinyvit_mlp2_fixture import pack_int8


SCHEMA = "sap-vpu-tinyvit-fc1-k128-int8-v1"
TOKENS = 2
INPUT_CHANNELS = 128
OUTPUT_CHANNELS = 2
CHUNK_K = 8


def require_matrix(value: Any, name: str, rows: int, columns: int) -> list[list[int]]:
    if not isinstance(value, list) or len(value) != rows:
        raise ValueError(f"{name} must have shape [{rows}, {columns}]")
    matrix: list[list[int]] = []
    for row_index, row in enumerate(value):
        if not isinstance(row, list) or len(row) != columns:
            raise ValueError(f"{name}[{row_index}] must have {columns} entries")
        if any(not isinstance(item, int) or isinstance(item, bool) or not -128 <= item <= 127 for item in row):
            raise ValueError(f"{name}[{row_index}] entries must be signed INT8")
        matrix.append(row)
    return matrix


def validate(raw: Any) -> tuple[list[list[int]], list[list[int]], list[list[int]]]:
    if not isinstance(raw, dict) or raw.get("schema") != "sap-vpu-tinyvit-mlp2-int8-v1":
        raise ValueError("invalid parent TinyViT activation fixture")
    fixture = raw.get("fc1_k128")
    if not isinstance(fixture, dict) or fixture.get("schema") != SCHEMA:
        raise ValueError(f"missing {SCHEMA} fixture")
    if fixture.get("chunk_k") != CHUNK_K:
        raise ValueError(f"fc1_k128.chunk_k must be {CHUNK_K}")
    inputs = require_matrix(fixture.get("input_tokens"), "input_tokens", TOKENS, INPUT_CHANNELS)
    weights = require_matrix(fixture.get("weights"), "weights", OUTPUT_CHANNELS, INPUT_CHANNELS)
    expected = fixture.get("expected_integer_output")
    if not isinstance(expected, list) or len(expected) != TOKENS:
        raise ValueError("expected_integer_output must have shape [2, 2]")
    expected = [list(row) for row in expected]
    if any(len(row) != OUTPUT_CHANNELS or any(not isinstance(item, int) for item in row) for row in expected):
        raise ValueError("expected_integer_output must have integer shape [2, 2]")
    calculated = [
        [sum(inputs[token][k] * weights[output][k] for k in range(INPUT_CHANNELS)) for output in range(OUTPUT_CHANNELS)]
        for token in range(TOKENS)
    ]
    if calculated != expected:
        raise ValueError("expected_integer_output does not match the INT8 matrices")
    return inputs, weights, expected


def chunk_words(matrix: list[list[int]]) -> list[int]:
    words: list[int] = []
    for chunk_base in range(0, INPUT_CHANNELS, CHUNK_K):
        for row_index, row in enumerate(matrix):
            words.append(pack_int8(row[chunk_base : chunk_base + 4], f"row{row_index}_chunk{chunk_base}"))
            words.append(pack_int8(row[chunk_base + 4 : chunk_base + 8], f"row{row_index}_chunk{chunk_base + 4}"))
    return words


def write_include(path: Path, inputs: list[list[int]], weights: list[list[int]], expected: list[list[int]]) -> None:
    lines = [
        "/* Generated by prepare_tinyvit_fc1_k128.py; do not edit. */",
        f".equ TINYVIT_FC1_K128_CHUNKS, {INPUT_CHANNELS // CHUNK_K}",
    ]
    for token in range(TOKENS):
        for output in range(OUTPUT_CHANNELS):
            lines.append(f".equ TINYVIT_FC1_K128_EXPECTED_{token}{output}, {expected[token][output]}")
    lines.extend((".section .rodata", ".balign 4", "tinyvit_fc1_k128_inputs:"))
    lines.extend(f"  .word 0x{word:08x}" for word in chunk_words(inputs))
    lines.extend((".balign 4", "tinyvit_fc1_k128_weights:"))
    lines.extend(f"  .word 0x{word:08x}" for word in chunk_words(weights))
    lines.append(".section .text.start")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def self_test() -> None:
    root = Path(__file__).resolve().parents[1]
    raw = json.loads((root / "sw/baremetal/fixtures/tinyvit_mlp2_activation.json").read_text(encoding="ascii"))
    inputs, weights, expected = validate(raw)
    assert expected == [[-15845, -5456], [6267, -5774]]
    assert len(chunk_words(inputs)) == 64
    assert len(chunk_words(weights)) == 64
    with tempfile.TemporaryDirectory() as directory:
        output = Path(directory) / "fixture.inc"
        write_include(output, inputs, weights, expected)
        assert ".equ TINYVIT_FC1_K128_CHUNKS, 16" in output.read_text(encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fixture", type=Path, nargs="?")
    parser.add_argument("--asm", type=Path)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    try:
        if args.self_test:
            if args.fixture or args.asm:
                parser.error("--self-test does not accept fixture output arguments")
            self_test()
        elif not args.fixture or not args.asm:
            parser.error("fixture and --asm are required")
        else:
            inputs, weights, expected = validate(json.loads(args.fixture.read_text(encoding="ascii")))
            write_include(args.asm, inputs, weights, expected)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"TinyViT FC1 K=128 fixture failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
